In [41]:
import torch
print(torch.cuda.is_available())
print(torch.backends.mps.is_available())

True
False


# GPU 사용하기

윈도우 -> cuda, MAC -> mps

In [42]:
print(torch.__version__)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('mps') if torch.backends.mps.is_available() else torch.device('cpu')
device.type

2.1.2+cu118


'cuda'

## GPU 사용하는지 확인하기
코드 돌릴 때 GPU 사용하는지 확인해보기

In [43]:
# 추가 모듈 로드
import torch.nn as nn
import time

# torch 데이터 유형, 백엔드 설정
dtype = torch.float

# 3개 변수를 가진 다중회귀 모형 샘플 데이터 설정
x = torch.randint(10, (100, 3),device = device, dtype=dtype)
y = torch.randint(100, 200, (100, 1),device = device, dtype=dtype)

# 선형 모델 구성
ml_model = nn.Linear(3,1) # 3x1 (변수 할당)
ml_model.to(device)

# 옵티마이저
optimizer = torch.optim.SGD(ml_model.parameters(), lr = 1e-3)

# epoch 설정
total_epoch = 3000

# 학습 시작
train_start = time.time()
for epoch in range(total_epoch+1):

    # 예측값
    prediction = ml_model(x)

    # 비용 (Class가 아니므로 nn.functional 사용)
    loss = nn.functional.mse_loss(prediction, y)

    # 역전파
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

	# 중간 기록
    if epoch % 100 == 0:
        print(f"Epoch {epoch}/{total_epoch},\t loss : {loss.item()}")
        
train_end = time.time()

# 학습 소요 시간 확인
print()
print(device.type, '학습 소요시간 ',train_end-train_start)

Epoch 0/3000,	 loss : 22645.181640625
Epoch 100/3000,	 loss : 3185.1181640625
Epoch 200/3000,	 loss : 3059.127685546875
Epoch 300/3000,	 loss : 2940.667236328125
Epoch 400/3000,	 loss : 2827.974365234375
Epoch 500/3000,	 loss : 2720.717041015625
Epoch 600/3000,	 loss : 2618.6328125
Epoch 700/3000,	 loss : 2521.471923828125
Epoch 800/3000,	 loss : 2428.99560546875
Epoch 900/3000,	 loss : 2340.978759765625
Epoch 1000/3000,	 loss : 2257.206787109375
Epoch 1100/3000,	 loss : 2177.474365234375
Epoch 1200/3000,	 loss : 2101.58642578125
Epoch 1300/3000,	 loss : 2029.3583984375
Epoch 1400/3000,	 loss : 1960.6134033203125
Epoch 1500/3000,	 loss : 1895.183349609375
Epoch 1600/3000,	 loss : 1832.908203125
Epoch 1700/3000,	 loss : 1773.6363525390625
Epoch 1800/3000,	 loss : 1717.2227783203125
Epoch 1900/3000,	 loss : 1663.529296875
Epoch 2000/3000,	 loss : 1612.42529296875
Epoch 2100/3000,	 loss : 1563.78564453125
Epoch 2200/3000,	 loss : 1517.4913330078125
Epoch 2300/3000,	 loss : 1473.4293212890

# Pytorch Tensor Allocation

In [44]:
# 1D tensor(vector)
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print("rank :", t.dim())
print("shape :", t.shape)
print("shape :", t.size())

rank : 1
shape : torch.Size([7])
shape : torch.Size([7])


In [45]:
# 2D tensor(matrix)
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]
                       ])
print(t.dim(), t.size(), sep = '\n')
print(t[:, 1], t[:, 1].size(), sep = '\n')

print(t[:, :-1]) # :-1 = 0:2

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [46]:
# matmul vs. mul
m1 = torch.tensor([[1, 2],
                   [3, 4]])
m2 = torch.tensor([1, 2]) # m2 = torch.tensor([[1], [2]])랑 결과 다르게 나옴.
print(m1.shape, m2.shape)
print(m1.matmul(m2))
print(m1.mul(m2)) # m1 * m2

torch.Size([2, 2]) torch.Size([2])
tensor([ 5, 11])
tensor([[1, 4],
        [3, 8]])


In [47]:
# mean, sum
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

print(t.sum(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([3., 7.])


In [48]:
# max, argmax
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t.max(), t.max(dim=0), t.argmax(dim=1), sep = '\n') # max에 dim 인자를 주면 argmax도 함께 리턴

print("Max :", t.max(dim=0)[0])
print("Argmax :", t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([1, 1])
Max : tensor([3., 4.])
Argmax : tensor([1, 1])


In [49]:
# view
import numpy as np
t = np.array([[[0, 1, 2],
              [3, 4, 5],],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.view([-1, 3]), ft.view([-1, 3]).shape, sep = '\n')

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [50]:
# squeeze, unsqueeze
ft = torch.FloatTensor([[0], [1], [2]])
print(ft, ft.shape)
ft_new = ft.squeeze()
print(ft_new, ft_new.shape)
ft_renew = ft_new.unsqueeze(dim=-1) # unsqueeze(-1) 해도 결과 같음.
print(ft_renew, ft_renew.shape)

tensor([[0.],
        [1.],
        [2.]]) torch.Size([3, 1])
tensor([0., 1., 2.]) torch.Size([3])
tensor([[0.],
        [1.],
        [2.]]) torch.Size([3, 1])


In [51]:
# concatenate, stack
x, y = torch.FloatTensor([[1, 2], [3, 4]]), torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

x, y, z = torch.FloatTensor([1, 4]), torch.FloatTensor([2, 5]), torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.cat([x, y, z], dim = 0))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([1., 4., 2., 5., 3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
# ones_like, zeros_like
x = torch.FloatTensor([[0, 1, 2], [3, 4, 5]])
print(torch.ones_like(x), torch.zeros_like(x), sep = '\n')

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [53]:
# in-place operation
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
